# Generated by Django 5.2.3 on 2025-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_order_customer_order_products_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
